### PR TITLE
Shrink image size

### PR DESCRIPTION
**Pull request by cyberhck**
Here's a PR to shrink image size. Once this is deployed, I'll write an article on how to use this with proper volume mounting and interactive debugging in PhpStorm.

### CODE REVIEW

**Comment by cyberhck** [comment]
Also this is minimal phalcon without anything at all, all those pinba and other extensions one will have to write their own dockerfile and extend from `phalconphp/php:7` or `phalconphp/php-fpm:7`

**Comment by niden** [comment]
Can we leave the current image as is and create one that is just what you sent?

Perhaps name that one php7-min?

The reason behind this, is because with the current image someone can be up and running in no time without having to rebuild the docker image.

Thoughts?

**Comment by cyberhck** [comment]
Actually that's not a bad idea, I was just thinking if we actually need that one, because with the current setup, they can still be up and running. But yeah, totally doable. First let me make this work on PhpStorm (I'm having trouble with auto complete for phalcon)

**Comment by cyberhck** [comment]
hi @niden , @sergeyklay  , on a second note, everyone who want to use Phalcon with docker on production will do  a docker pull Phalcon/php-fpm:7 after seeing php:fpm in docker hub, what I suggest is: let's keep the old phalcon by name phalcon-starter-kit, or something along that lines, what do you say?

**Comment by cyberhck** [comment]
also I've got a problem here, I'm not sure if everything is working fine.
I copied this file as my index file: https://github.com/phalcon/mvc/blob/master/micro/index.php
Now no matter which route I go to, it says "Welcome!" only calls `/` route.
I'm sure it's not a docker issue because `var_dump($_SERVER['REQUEST_URI']);` shows

> string(19) "/say/hello/nishchal"

What am I doing wrong?

**Comment by niden** [comment]
@cyberhck The current docker image is primarily for development. We can definitely create a slim one just for production which will utilize smaller size and will be blank, with very little if any extensions installed for people to use.

The suggestion that @sergeyklay mentioned earlier with an alpine container should be sufficient for production use. 

As for the names, I am open to suggestion so long as we make it very clear on what each container is.

**Comment by niden** [comment]
@cyberhck is your .htaccess correct with the relevant redirections? If you are using nginx do you have the relevant `try` directive up there?

**Comment by cyberhck** [comment]
the reason people use alpine is because of it's size, if you see, php7.0-alpine is around 56MB, whereas the alpine which we published is around 300MB, Okay, let's come up with the name for small one.

And for production they will not be consuming this directly, they'll write a dockerfile which extends phalcon's php and they add few extensions on their own which they need.

**Comment by cyberhck** [comment]
@niden if I replace `$app->handle()` with `$app->handle($_SERVER['REQUEST_URI']);` , it starts working flawlessly

**Comment by cyberhck** [comment]
let's close this one, since I lost track of this on my local copy and I've no idea what I did in here :)

**Pull request closed without merging**
